### ISSUE TITLE
Using Drop Folder with a lot of utf-8 Names Results in not Importing Files

### ISSUE THREAD

**Issue by bigretromike** [japanesemediamanager/ShokoServer#443]
```
[2016-09-27 09:32:15:953] Error|BackgroundWorker.OnDoWork => MainWindow.workerScanFolder_DoWork => Importer.RunImport_ScanFolder System.InvalidOperationException: Collection was modified; enumeration operation may not execute.
   at System.ThrowHelper.ThrowInvalidOperationException(ExceptionResource resource)
   at System.Collections.Generic.Dictionary`2.ValueCollection.Enumerator.MoveNext()
   at System.Linq.Enumerable.WhereEnumerableIterator`1.MoveNext()
   at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   at JMMServer.Importer.RunImport_ScanFolder(Int32 importFolderID) in D:\My Files\Documents\GitHub\jmmserver\JMMServer\Importer.cs:line 276
```

Using 3.6.1.0

Nothing else is using this directory. When I first restarted jmmserver it scanned and added 12 items, but then still hit this error.

First I thinked it saves all items that was unrecognized so it don't scan it anymore but then I added more than 12 items and nothing get scaned and this was inside log.

**Comment by da3dsoul** [comment]
A concurrent modification exception is what it looks like. Hmm

**Comment by bigretromike** [comment]
Do we have async multi thread architecture for scanning import folders? as nothing else use that folder

**Comment by da3dsoul** [comment]
I don't think so, which is what confuses me

**Comment by bigretromike** [comment]
also, after removing import folder from jmm, readding it, scanning started to work - even without any restarts.

**Comment by bigretromike** [comment]
Update: making another input folder but with "watch dog" is workaround for this as it scan each folder I drop there instead of making list of items and itereate them

**Comment by bigretromike** [comment]
I have tested this few times with latest build and it looks like I don't get that error anymore.
