### ISSUE TITLE
Renamer fails to add files

### ISSUE THREAD

**Issue by CtrlAltDefeat94** [japanesemediamanager/ShokoServer#528]
**This is on the beta, version 3.7.0.904**

When I try to add files to the renamer it lists 0 files and the server log shows this error:
```
[2016-12-11 22:02:46:645] Error|SyncMethodInvoker.Invoke => <no type>.SyncInvokeGetVideoLocalsForAnime => JMMServiceImplementation.GetVideoLocalsForAnime System.ArgumentException: 'path' cannot be an empty string.
Parameter name: path
   at Pri.LongPath.Path.NormalizeLongPath(String path, String parameterName) in D:\My Files\Documents\GitHub\jmmserver\JMMServer\Entities\TvDB_Series.cs:line 0
   at JMMServer.Entities.VideoLocal.GetMediaFromUser(Int32 userID) in D:\My Files\Documents\GitHub\jmmserver\JMMServer\Entities\VideoLocal.cs:line 512
   at JMMServer.Entities.VideoLocal.ToContract(Int32 userID) in D:\My Files\Documents\GitHub\jmmserver\JMMServer\Entities\VideoLocal.cs:line 505
   at System.Linq.Enumerable.WhereSelectListIterator`2.MoveNext()
   at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   at JMMServer.JMMServiceImplementation.GetVideoLocalsForAnime(Int32 animeID, Int32 userID) in D:\My Files\Documents\GitHub\jmmserver\JMMServer\JMMServiceImplementation.cs:line 8324
[2016-12-11 22:03:29:599] Error|SyncMethodInvoker.Invoke => <no type>.SyncInvokeGetVideoLocalsForAnime => JMMServiceImplementation.GetVideoLocalsForAnime System.ArgumentException: 'path' cannot be an empty string.
Parameter name: path
   at Pri.LongPath.Path.NormalizeLongPath(String path, String parameterName) in D:\My Files\Documents\GitHub\jmmserver\JMMServer\Entities\TvDB_Series.cs:line 0
   at JMMServer.Entities.VideoLocal.GetMediaFromUser(Int32 userID) in D:\My Files\Documents\GitHub\jmmserver\JMMServer\Entities\VideoLocal.cs:line 512
   at JMMServer.Entities.VideoLocal.ToContract(Int32 userID) in D:\My Files\Documents\GitHub\jmmserver\JMMServer\Entities\VideoLocal.cs:line 505
   at System.Linq.Enumerable.WhereSelectListIterator`2.MoveNext()
   at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   at JMMServer.JMMServiceImplementation.GetVideoLocalsForAnime(Int32 animeID, Int32 userID) in D:\My Files\Documents\GitHub\jmmserver\JMMServer\JMMServiceImplementation.cs:line 8324
```

I am unsure if it's related to this, but the renamer seems to forget to add extentions (randomly) as well

**Comment by da3dsoul** [comment]
Hopefully this is now fixed

**Comment by CtrlAltDefeat94** [comment]
Not working for me in 3.7.0.1038

**Comment by da3dsoul** [comment]
Is that latest?

**Comment by CtrlAltDefeat94** [comment]
That's what I pulled from the website a few hours back

**Comment by da3dsoul** [comment]
And more importantly, is it the same error

**Comment by CtrlAltDefeat94** [comment]
This is the error now;
`[2017-01-22 16:41:08:657] Error|SyncMethodInvoker.Invoke => <no type>.SyncInvokeRandomFileRenamePreview => JMMServiceImplementation.RandomFileRenamePreview System.ArgumentException: 'path' cannot be an empty string.
Parameter name: path
   at Pri.LongPath.Path.NormalizeLongPath(String path, String parameterName) in C:\projects\jmmserver\JMMServer\Repositories\Direct\FileNameHashRepository.cs:line 0
   at JMMServer.Entities.VideoLocal.GetMediaFromUser(Int32 userID) in C:\projects\jmmserver\JMMServer\Entities\VideoLocal.cs:line 513
   at JMMServer.Entities.VideoLocal.ToContract(Int32 userID) in C:\projects\jmmserver\JMMServer\Entities\VideoLocal.cs:line 506
   at System.Linq.Enumerable.WhereSelectListIterator`2.MoveNext()
   at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   at JMMServer.JMMServiceImplementation.RandomFileRenamePreview(Int32 maxResults, Int32 userID) in C:\projects\jmmserver\JMMServer\JMMServiceImplementation.cs:line 8156
`

**Comment by da3dsoul** [comment]
Okay... I'll take an even closer look at it

**Comment by deusxanime** [comment]
+1 on this and also replying to get notifications. Also it cannot find anything when doing File Search, selecting File Name, and typing in a search query. Everything I search for just returns with 0 files. Both started at the same time a couple weeks back and can't think of anything to correlate with why. Running 3.7.0.6 and it wasn't after an upgrade or any change I can remember.

Hopefully da3dsoul's fix works in next version, because my files that I need to rename are piling up!

**Comment by Vorador2** [comment]
Same problem here, file renamer doesn't display anything. Log shows same error than CtrlAltDefeat94.

**Comment by da3dsoul** [comment]
I can verify that there is very little chance of this happening on the next version.

**Comment by da3dsoul** [comment]
Fixed for sure.

**Comment by deusxanime** [comment]
I downgraded to v3.6.0.4 to get renamer usable. What version should have the fix, so I know when I can try upgrading again? Thanks for you work!

**Comment by da3dsoul** [comment]
The next one to be released

**Comment by da3dsoul** [comment]
I'm not sure what number we'll give it

**Comment by deusxanime** [comment]
OK nbd, I'll just keep an eye out for whatever comes next.
