### ISSUE TITLE
JMMserver crashes during startup, xml parsing error

### ISSUE THREAD

**Issue by bond4u** [japanesemediamanager/ShokoServer#542]
Noticed that JMMServer had disappeared. Tried to start it, but it keeps crashing.
Seems to be crashing because of xml error.
There's also occurrence of #532 - crashes when tvdb responds with 404.
[2017-01-04.txt](https://github.com/japanesemediamanager/ShokoServer/files/683447/2017-01-04.txt)

**Comment by ElementalCrisis** [comment]
Looks like you're running an older version, can you try updating to the latest version? 

http://jmediamanager.org/downloads/

**Comment by bond4u** [comment]
Okay, installed 3.7. DbRegen is slow - 150/10547... We'll see in the morning how it works out.

**Comment by da3dsoul** [comment]
Yeah that'll prolly take an hour.

**Comment by bond4u** [comment]
Ok, it has not crashed, import is running.

**Comment by bond4u** [comment]
I haven't noticed it before - it attempts to rename files, but fails because ":" in file name.
Rename usually happens during import, not out of blue?

[2017-01-04 04:28:09:024] Info|BackgroundWorker.OnDoWork => CommandProcessorGeneral.workerCommands_DoWork => CommandRequest_ProcessFile.ProcessCommand Processing File: 104780
[2017-01-04 04:28:09:964] Info|<>c.<ProcessFile_AniDB>b__16_0 => VideoLocal_Place.RenameIfRequired => VideoLocal_Place.RenameFile Renaming file From (P:\_ani\2007\Darker Than Black Kuro no Keiyakusha\(project-gxs)_Darker_Than_Black_-_22_(10bit_BD_720p)_(Coalgirls_sudo).mkv) to (P:\_ani\2007\Darker Than Black Kuro no Keiyakusha\[Project-gxs] Darker Than Black: Kuro no Keiyakusha - 22 [720p] [5E738EBB].mkv)....
[2017-01-04 04:28:10:028] Info|<>c.<ProcessFile_AniDB>b__16_0 => VideoLocal_Place.RenameIfRequired => VideoLocal_Place.RenameFile Renaming file FAILED! From (P:\_ani\2007\Darker Than Black Kuro no Keiyakusha\(project-gxs)_Darker_Than_Black_-_22_(10bit_BD_720p)_(Coalgirls_sudo).mkv) to (P:\_ani\2007\Darker Than Black Kuro no Keiyakusha\[Project-gxs] Darker Than Black: Kuro no Keiyakusha - 22 [720p] [5E738EBB].mkv) - One or more errors occurred.
[2017-01-04 04:28:10:028] Error|<>c.<ProcessFile_AniDB>b__16_0 => VideoLocal_Place.RenameIfRequired => VideoLocal_Place.RenameFile System.AggregateException: One or more errors occurred. ---> System.ArgumentException: The filename, directory name, or volume label syntax is incorrect.

Parameter name: path
   at Pri.LongPath.File.Move(String sourcePath, String destinationPath) in D:\My Files\Documents\GitHub\jmmserver\JMMServer\FileHelper\Subtitles\SubtitleHelper.cs:line 0
   at NutzCode.CloudFileSystem.Plugins.LocalFileSystem.LocalFile.<RenameAsync>d__28.MoveNext() in D:\My Files\Documents\GitHub\jmmserver\NutzCode.CloudFileSystem\NutzCode.CloudFileSystem.Plugins.LocalFileSystem\LocalFile.cs:line 113
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at NutzCode.CloudFileSystem.SyncExtensions.<>c__DisplayClass5_0.<<Rename>b__0>d.MoveNext() in D:\My Files\Documents\GitHub\jmmserver\NutzCode.CloudFileSystem\NutzCode.CloudFileSystem\SyncExtensions.cs:line 39
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task`1.GetResultCore(Boolean waitCompletionNotification)
   at NutzCode.CloudFileSystem.SyncExtensions.Rename(IObject obj, String newname) in D:\My Files\Documents\GitHub\jmmserver\NutzCode.CloudFileSystem\NutzCode.CloudFileSystem\SyncExtensions.cs:line 0
   at JMMServer.Entities.VideoLocal_Place.RenameFile(String renameScript) in D:\My Files\Documents\GitHub\jmmserver\JMMServer\Entities\VideoLocal_Place.cs:line 71
---> (Inner Exception #0) System.ArgumentException: The filename, directory name, or volume label syntax is incorrect.

Parameter name: path
   at Pri.LongPath.File.Move(String sourcePath, String destinationPath) in D:\My Files\Documents\GitHub\jmmserver\JMMServer\FileHelper\Subtitles\SubtitleHelper.cs:line 0
   at NutzCode.CloudFileSystem.Plugins.LocalFileSystem.LocalFile.<RenameAsync>d__28.MoveNext() in D:\My Files\Documents\GitHub\jmmserver\NutzCode.CloudFileSystem\NutzCode.CloudFileSystem.Plugins.LocalFileSystem\LocalFile.cs:line 113
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at NutzCode.CloudFileSystem.SyncExtensions.<>c__DisplayClass5_0.<<Rename>b__0>d.MoveNext() in D:\My Files\Documents\GitHub\jmmserver\NutzCode.CloudFileSystem\NutzCode.CloudFileSystem\SyncExtensions.cs:line 39<---

**Comment by RickDB** [comment]
Could try the following:

- Stop Shoko Server
- Move any old logs out of the way
- Install latest daily build:

http://jmediamanager.org/files/daily/JMMServer/

- Start Shoko Server again
- Wait a few minutes then post log on pastebin or gist.github.com (easier to read)

That way we should be able to see more clearly where it goes wrong :)

**Comment by bigretromike** [comment]
@bond4u was your problem solved by using latest daily build ? as RickDB stated

**Comment by da3dsoul** [comment]
Looking at those. They should all be fixed. Reopen if otherwise
