### ISSUE TITLE
"could not move file" error in log

### ISSUE THREAD

**Issue by bond4u** [japanesemediamanager/ShokoServer#562]
Shoko has been slow lately and so I checked log files and there are lots of "Could not MOVE" and "semaphore timeout" errors.
There's no indication where it tried to move the file.
Version 3.7.0.3, but I've seen those errors before in 3.6 as well.
 
```
[2017-01-28 12:48:20:648] Info|<>c.<ProcessFile_AniDB>b__16_0 => VideoLocal_Place.RenameIfRequired => VideoLocal_Place.RenameFile Renaming file From (G:\_torrentz\_removed\_2017\01\[NoobSubs] Haganai~Boku wa Tomodachi ga Sukunai + NEXT (720p Blu-ray Dual Audio 8bit AAC)\[NoobSubs] Haganai NEXT 06 (720p Blu-ray Dual Audio 8bit AAC)[B7C24B39].mkv) to (G:\_torrentz\_removed\_2017\01\[NoobSubs] Haganai~Boku wa Tomodachi ga Sukunai + NEXT (720p Blu-ray Dual Audio 8bit AAC)\[NoobSubs] Boku wa Tomodachi ga Sukunai Next - 06 [720p] [B7C24B39].mkv)....
[2017-01-28 12:48:20:648] Info|<>c.<ProcessFile_AniDB>b__16_0 => VideoLocal_Place.RenameIfRequired => VideoLocal_Place.RenameFile Renaming file SUCCESS! From (G:\_torrentz\_removed\_2017\01\[NoobSubs] Haganai~Boku wa Tomodachi ga Sukunai + NEXT (720p Blu-ray Dual Audio 8bit AAC)\[NoobSubs] Haganai NEXT 06 (720p Blu-ray Dual Audio 8bit AAC)[B7C24B39].mkv) to (G:\_torrentz\_removed\_2017\01\[NoobSubs] Haganai~Boku wa Tomodachi ga Sukunai + NEXT (720p Blu-ray Dual Audio 8bit AAC)\[NoobSubs] Boku wa Tomodachi ga Sukunai Next - 06 [720p] [B7C24B39].mkv)
[2017-01-28 12:48:20:648] Info|BackgroundWorker.WorkerThreadStart => BackgroundWorker.OnDoWork => MainWindow.workerFileEvents_DoWork New file detected: G:\_torrentz\_removed\_2017\01\[NoobSubs] Haganai~Boku wa Tomodachi ga Sukunai + NEXT (720p Blu-ray Dual Audio 8bit AAC)\[NoobSubs] Boku wa Tomodachi ga Sukunai Next - 06 [720p] [B7C24B39].mkv: Renamed
[2017-01-28 12:48:20:648] Info|BackgroundWorker.WorkerThreadStart => BackgroundWorker.OnDoWork => MainWindow.workerFileEvents_DoWork Found file G:\_torrentz\_removed\_2017\01\[NoobSubs] Haganai~Boku wa Tomodachi ga Sukunai + NEXT (720p Blu-ray Dual Audio 8bit AAC)\[NoobSubs] Boku wa Tomodachi ga Sukunai Next - 06 [720p] [B7C24B39].mkv
[2017-01-28 12:48:20:677] Info|BackgroundWorker.OnDoWork => CommandProcessorHasher.workerCommands_DoWork => CommandRequest_HashFile.ProcessCommand Hashing File: G:\_torrentz\_removed\_2017\01\[NoobSubs] Haganai~Boku wa Tomodachi ga Sukunai + NEXT (720p Blu-ray Dual Audio 8bit AAC)\[NoobSubs] Boku wa Tomodachi ga Sukunai Next - 06 [720p] [B7C24B39].mkv

[2017-01-28 12:57:28:182] Error|CommandRequest_ProcessFile.ProcessFile_AniDB => List`1.ForEach => VideoLocal_Place.MoveFileIfRequired Could not MOVE file: G:\_torrentz\_removed\_2017\01\[NoobSubs] Haganai~Boku wa Tomodachi ga Sukunai + NEXT (720p Blu-ray Dual Audio 8bit AAC)\[NoobSubs] Boku wa Tomodachi ga Sukunai Next - 06 [720p] [B7C24B39].mkv -- System.AggregateException: One or more errors occurred. ---> System.IO.IOException: The semaphore timeout period has expired.

   at Pri.LongPath.Directory.BeginFind(String normalizedPathWithSearchPattern, WIN32_FIND_DATA& findData) in D:\My Files\Documents\GitHub\jmmserver\JMMServer\Repositories\Direct\Trakt_FriendRepository.cs:line 0
   at Pri.LongPath.Directory.<EnumerateFileSystemIterator>d__16.MoveNext() in D:\My Files\Documents\GitHub\jmmserver\JMMServer\Repositories\Direct\Trakt_FriendRepository.cs:line 0
   at System.Linq.Buffer`1..ctor(IEnumerable`1 source)
   at System.Linq.Enumerable.ToArray[TSource](IEnumerable`1 source)
   at Pri.LongPath.DirectoryInfo.GetDirectories() in D:\My Files\Documents\GitHub\jmmserver\JMMServer\Repositories\Direct\Trakt_FriendRepository.cs:line 0
   at NutzCode.CloudFileSystem.Plugins.LocalFileSystem.DirectoryImplementation.<PopulateAsync>d__26.MoveNext() in D:\My Files\Documents\GitHub\jmmserver\NutzCode.CloudFileSystem\NutzCode.CloudFileSystem.Plugins.LocalFileSystem\DirectoryImplementation.cs:line 72
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at NutzCode.CloudFileSystem.DirectoryCache.DirectoryCache.<GetFromPath>d__2.MoveNext() in D:\My Files\Documents\GitHub\jmmserver\NutzCode.CloudFileSystem\NutzCode.CloudFileSystem\DirectoryCache\DirectoryCache.cs:line 31
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at NutzCode.CloudFileSystem.DirectoryCache.DirectoryCache.<ObjectFromPath>d__3.MoveNext() in D:\My Files\Documents\GitHub\jmmserver\NutzCode.CloudFileSystem\NutzCode.CloudFileSystem\DirectoryCache\DirectoryCache.cs:line 119
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at NutzCode.CloudFileSystem.Plugins.LocalFileSystem.LocalFileSystem.<ResolveAsync>d__7.MoveNext() in D:\My Files\Documents\GitHub\jmmserver\NutzCode.CloudFileSystem\NutzCode.CloudFileSystem.Plugins.LocalFileSystem\LocalFileSystem.cs:line 82
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at NutzCode.CloudFileSystem.SyncExtensions.<>c__DisplayClass2_0.<<Resolve>b__0>d.MoveNext() in D:\My Files\Documents\GitHub\jmmserver\NutzCode.CloudFileSystem\NutzCode.CloudFileSystem\SyncExtensions.cs:line 24
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task`1.GetResultCore(Boolean waitCompletionNotification)
   at NutzCode.CloudFileSystem.SyncExtensions.Resolve(IFileSystem filesys, String path) in D:\My Files\Documents\GitHub\jmmserver\NutzCode.CloudFileSystem\NutzCode.CloudFileSystem\SyncExtensions.cs:line 0
   at JMMServer.Entities.VideoLocal_Place.MoveFileIfRequired() in D:\My Files\Documents\GitHub\jmmserver\JMMServer\Entities\VideoLocal_Place.cs:line 428
---> (Inner Exception #0) System.IO.IOException: The semaphore timeout period has expired.

   at Pri.LongPath.Directory.BeginFind(String normalizedPathWithSearchPattern, WIN32_FIND_DATA& findData) in D:\My Files\Documents\GitHub\jmmserver\JMMServer\Repositories\Direct\Trakt_FriendRepository.cs:line 0
   at Pri.LongPath.Directory.<EnumerateFileSystemIterator>d__16.MoveNext() in D:\My Files\Documents\GitHub\jmmserver\JMMServer\Repositories\Direct\Trakt_FriendRepository.cs:line 0
   at System.Linq.Buffer`1..ctor(IEnumerable`1 source)
   at System.Linq.Enumerable.ToArray[TSource](IEnumerable`1 source)
   at Pri.LongPath.DirectoryInfo.GetDirectories() in D:\My Files\Documents\GitHub\jmmserver\JMMServer\Repositories\Direct\Trakt_FriendRepository.cs:line 0
   at NutzCode.CloudFileSystem.Plugins.LocalFileSystem.DirectoryImplementation.<PopulateAsync>d__26.MoveNext() in D:\My Files\Documents\GitHub\jmmserver\NutzCode.CloudFileSystem\NutzCode.CloudFileSystem.Plugins.LocalFileSystem\DirectoryImplementation.cs:line 72
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at NutzCode.CloudFileSystem.DirectoryCache.DirectoryCache.<GetFromPath>d__2.MoveNext() in D:\My Files\Documents\GitHub\jmmserver\NutzCode.CloudFileSystem\NutzCode.CloudFileSystem\DirectoryCache\DirectoryCache.cs:line 31
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at NutzCode.CloudFileSystem.DirectoryCache.DirectoryCache.<ObjectFromPath>d__3.MoveNext() in D:\My Files\Documents\GitHub\jmmserver\NutzCode.CloudFileSystem\NutzCode.CloudFileSystem\DirectoryCache\DirectoryCache.cs:line 119
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at NutzCode.CloudFileSystem.Plugins.LocalFileSystem.LocalFileSystem.<ResolveAsync>d__7.MoveNext() in D:\My Files\Documents\GitHub\jmmserver\NutzCode.CloudFileSystem\NutzCode.CloudFileSystem.Plugins.LocalFileSystem\LocalFileSystem.cs:line 82
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at NutzCode.CloudFileSystem.SyncExtensions.<>c__DisplayClass2_0.<<Resolve>b__0>d.MoveNext() in D:\My Files\Documents\GitHub\jmmserver\NutzCode.CloudFileSystem\NutzCode.CloudFileSystem\SyncExtensions.cs:line 24<---
```

**Comment by da3dsoul** [comment]
I'm going to trim this to the needed info.

**Comment by da3dsoul** [comment]
@maxpiva there is an error in DirectoryImplementation.GetDirectories(). I tried to figure out what was wrong and fix it, but it was beyond me. I've also not been able to reproduce the error.

Situations I've heard it occurring more often are with mapped drives.

**Comment by bond4u** [comment]
G: is internal HDD, but I have several USB HDDs. One of them sometimes stops working - shows no contents.

**Comment by bigretromike** [comment]
Imo we cannot handle all hardware issues.

Probabbly the best bet is to tweak power settings on your windows so it wont turn usb drive of after inactive.

Or we have to handle "usb attached" drives somehow but that os specific imo; 
@ElementalCrisis what you think ?

**Comment by Cazzar** [comment]
We already attempt to move and rename after various timeouts, if the USB is
powering down to save power, after first poll it should wake up anyway

**Comment by ElementalCrisis** [comment]
I've seen this error before, if it is indeed caused by an external drive in a reduced power state then you're right @bigretromike, there's nothing we can do. However, my main anime folder is an external drive and what @Cazzar described is what mine does. It's entirely possible there's an underlying issue here that could be related to Shoko or specific @bond4u setup that we should attempt to figure out.

**Comment by bigretromike** [comment]
@Cazzar it should but from logs it look like it dosn't; I would try with power state tweak and see how that goes.

**Comment by bigretromike** [comment]
@bond4u how the energy tweak went ? 
If the issue is still present on daily build please reopen.

**Comment by bond4u** [comment]
I haven't tweaked anything. The device has not malfunctioned for last couple of months. Haven't seen this in logs for a while. Go figure...
