### ISSUE TITLE
Error in DirectoryImplementation.GetDirectories

### ISSUE THREAD

**Issue by Cazzar** [japanesemediamanager/ShokoServer#572]
## LOG FILE

```
[2017-02-03 16:46:46:663] Error|BackgroundWorker.WorkerThreadStart => BackgroundWorker.OnDoWork => MainWindow.workerRemoveMissing_DoWork System.AggregateException: One or more errors occurred. ---> System.IO.FileNotFoundException: The system cannot find the file specified.

   at Pri.LongPath.Directory.EnumerateNormalizedFileSystemEntries(Boolean includeDirectories, Boolean includeFiles, SearchOption option, String normalizedPath, String normalizedSearchPattern) in C:\Users\me\ShokoServer\JMMServer\Repositories\Direct\CommandRequestRepository.cs:line 0
   at Pri.LongPath.Directory.GetDirectories(String path) in C:\Users\me\ShokoServer\JMMServer\Repositories\Direct\CommandRequestRepository.cs:line 0
   at Pri.LongPath.DirectoryInfo.GetDirectories() in C:\Users\me\ShokoServer\JMMServer\Repositories\Direct\CommandRequestRepository.cs:line 0
   at NutzCode.CloudFileSystem.Plugins.LocalFileSystem.DirectoryImplementation.<PopulateAsync>d__26.MoveNext() in C:\Users\me\ShokoServer\NutzCode.CloudFileSystem\NutzCode.CloudFileSystem.Plugins.LocalFileSystem\DirectoryImplementation.cs:line 72
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at NutzCode.CloudFileSystem.DirectoryCache.DirectoryCache.<GetFromPath>d__2.MoveNext() in C:\Users\me\ShokoServer\NutzCode.CloudFileSystem\NutzCode.CloudFileSystem\DirectoryCache\DirectoryCache.cs:line 31
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at NutzCode.CloudFileSystem.DirectoryCache.DirectoryCache.<ObjectFromPath>d__3.MoveNext() in C:\Users\me\ShokoServer\NutzCode.CloudFileSystem\NutzCode.CloudFileSystem\DirectoryCache\DirectoryCache.cs:line 119
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at NutzCode.CloudFileSystem.Plugins.LocalFileSystem.LocalFileSystem.<ResolveAsync>d__7.MoveNext() in C:\Users\me\ShokoServer\NutzCode.CloudFileSystem\NutzCode.CloudFileSystem.Plugins.LocalFileSystem\LocalFileSystem.cs:line 93
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at NutzCode.CloudFileSystem.SyncExtensions.<>c__DisplayClass2_0.<<Resolve>b__0>d.MoveNext() in C:\Users\me\ShokoServer\NutzCode.CloudFileSystem\NutzCode.CloudFileSystem\SyncExtensions.cs:line 24
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task`1.GetResultCore(Boolean waitCompletionNotification)
   at NutzCode.CloudFileSystem.SyncExtensions.Resolve(IFileSystem filesys, String path) in C:\Users\me\ShokoServer\NutzCode.CloudFileSystem\NutzCode.CloudFileSystem\SyncExtensions.cs:line 0
   at JMMServer.Importer.RemoveRecordsWithoutPhysicalFiles() in C:\Users\me\ShokoServer\JMMServer\Importer.cs:line 835
   at JMMServer.MainWindow.workerRemoveMissing_DoWork(Object sender, DoWorkEventArgs e) in C:\Users\me\ShokoServer\JMMServer\MainWindow.xaml.cs:line 2338
---> (Inner Exception #0) System.IO.FileNotFoundException: The system cannot find the file specified.

   at Pri.LongPath.Directory.EnumerateNormalizedFileSystemEntries(Boolean includeDirectories, Boolean includeFiles, SearchOption option, String normalizedPath, String normalizedSearchPattern) in C:\Users\me\ShokoServer\JMMServer\Repositories\Direct\CommandRequestRepository.cs:line 0
   at Pri.LongPath.Directory.GetDirectories(String path) in C:\Users\me\ShokoServer\JMMServer\Repositories\Direct\CommandRequestRepository.cs:line 0
   at Pri.LongPath.DirectoryInfo.GetDirectories() in C:\Users\me\ShokoServer\JMMServer\Repositories\Direct\CommandRequestRepository.cs:line 0
   at NutzCode.CloudFileSystem.Plugins.LocalFileSystem.DirectoryImplementation.<PopulateAsync>d__26.MoveNext() in C:\Users\me\ShokoServer\NutzCode.CloudFileSystem\NutzCode.CloudFileSystem.Plugins.LocalFileSystem\DirectoryImplementation.cs:line 72
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at NutzCode.CloudFileSystem.DirectoryCache.DirectoryCache.<GetFromPath>d__2.MoveNext() in C:\Users\me\ShokoServer\NutzCode.CloudFileSystem\NutzCode.CloudFileSystem\DirectoryCache\DirectoryCache.cs:line 31
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at NutzCode.CloudFileSystem.DirectoryCache.DirectoryCache.<ObjectFromPath>d__3.MoveNext() in C:\Users\me\ShokoServer\NutzCode.CloudFileSystem\NutzCode.CloudFileSystem\DirectoryCache\DirectoryCache.cs:line 119
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at NutzCode.CloudFileSystem.Plugins.LocalFileSystem.LocalFileSystem.<ResolveAsync>d__7.MoveNext() in C:\Users\me\ShokoServer\NutzCode.CloudFileSystem\NutzCode.CloudFileSystem.Plugins.LocalFileSystem\LocalFileSystem.cs:line 93
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at NutzCode.CloudFileSystem.SyncExtensions.<>c__DisplayClass2_0.<<Resolve>b__0>d.MoveNext() in C:\Users\me\ShokoServer\NutzCode.CloudFileSystem\NutzCode.CloudFileSystem\SyncExtensions.cs:line 24<--
```

**Note:** Locally compiled version a30f6c6e6e29c82da94cea44a22d4c79e5397052
## Description

Remove missing files throws an exception on missing files.

**Comment by da3dsoul** [comment]
This isn't a remove missing files error. This is a local file system error

**Comment by Cazzar** [comment]
weird, replicating it on my

**Comment by Cazzar** [comment]
Seems like this is working fine in later versions.
