### ISSUE TITLE
Connection Error

### ISSUE THREAD

**Issue by jmediamanager** [japanesemediamanager/ShokoServer#58]
**Reported by Craige1Emmott, May 16, 2013**

JMM Server can sometimes spam out error messages relating to a null object reference with the connection.

log attached.

Error example

```
Error|AniDBHelper.Login => AniDBCommand_Login.Process => AniDBUDPCommand.ProcessCommand System.ArgumentNullException: Value cannot be null.
Parameter name: remoteEP
   at System.Net.Sockets.Socket.SendTo(Byte[] buffer, Int32 offset, Int32 size, SocketFlags socketFlags, EndPoint remoteEP)
   at System.Net.Sockets.Socket.SendTo(Byte[] buffer, EndPoint remoteEP)
   at AniDBAPI.Commands.AniDBUDPCommand.ProcessCommand(Socket& soUDP, IPEndPoint& remoteIpEndPoint, String sessionID, Encoding enc) in C:\Projects\SVN\JMM\trunk\JMMServer\JMMServer\AniDB_API\Commands\AniDBUDPCommand.cs:line 105
```

**Comment by ElementalCrisis** [comment]
@craige1 do you still encounter this error? I'm unable to reproduce.

**Comment by bigretromike** [comment]
Look thru logs of almost 1 year now and not null exception with similar error.
Mayby something related with OS
