### ISSUE TITLE
Large files won't stream without chunked encoding

### ISSUE THREAD

**Issue by da3dsoul** [japanesemediamanager/ShokoServer#589]
## LOG FILE
```
[2017-02-26 13:43:25:239] Error|NancyHost.GotCallback => NancyHost.Process => <>c.<StartNancyHost>b__154_0 System.IO.IOException: Stream was too long.
   at System.IO.MemoryStream.Write(Byte[] buffer, Int32 offset, Int32 count)
   at System.IO.Stream.InternalCopyTo(Stream destination, Int32 bufferSize)
   at System.IO.Stream.CopyTo(Stream destination)
   at Nancy.Responses.StreamResponse.<>c__DisplayClass1.<GetResponseBodyDelegate>b__0(Stream stream)
   at Nancy.Hosting.Self.NancyHost.OutputWithContentLength(Response nancyResponse, HttpListenerResponse response)
   at Nancy.Hosting.Self.NancyHost.ConvertNancyResponseToResponse(Response nancyResponse, HttpListenerResponse response)
   at Nancy.Hosting.Self.NancyHost.Process(HttpListenerContext ctx)
```

## Description

Disabling chunked encoding causes streams to be converted to a memory stream and fully loaded before sending. This is slow, and causes a 'stream was too long' IOException when a file is too large for the RAM. We discovered this while making a streamer for video, but some players would not accept chunked encoding.

## Code Responsible
In NancyHost.cs:357 on both master and 1.x branches:

```
        private static void OutputWithContentLength(Response nancyResponse, HttpListenerResponse response)
        {
            byte[] buffer;
            using (var memoryStream = new MemoryStream())
            {
                nancyResponse.Contents.Invoke(memoryStream);
                buffer = memoryStream.ToArray();
            }

            var contentLength = (nancyResponse.Headers.ContainsKey("Content-Length")) ?
                Convert.ToInt64(nancyResponse.Headers["Content-Length"]) :
                buffer.Length;

            response.SendChunked = false;
            response.ContentLength64 = contentLength;

            using (var output = response.OutputStream)
            {
                using (var writer = new BinaryWriter(output))
                {
                    writer.Write(buffer);
                    writer.Flush();
                }
            }
        }
```

**Comment by da3dsoul** [comment]
@maxpiva, I didn't check the issue reporting guidelines for nancy, but most of the work is done here.

**Comment by maxpiva** [comment]
Thanks @da3dsoul Great description, That will help on my English issues

**Comment by maxpiva** [comment]
##Proposed Changes

```
private static void OutputWithContentLength(Response nancyResponse, HttpListenerResponse response)
        {
            response.SendChunked = false;
            long contentLength = 0;
            if (nancyResponse.Headers.ContainsKey("Content-Length"))
            {
                contentLength = Convert.ToInt64(nancyResponse.Headers["Content-Length"]);
                if (contentLength > 0)
                {
                    response.ContentLength64 = contentLength;
                    using (var output = response.OutputStream)
                    {
                        nancyResponse.Contents.Invoke(output);
                    }
                }
                return;
            }
            byte[] buffer;
            using (var memoryStream = new MemoryStream())
            {
                nancyResponse.Contents.Invoke(memoryStream);
                buffer = memoryStream.ToArray();
            }

            contentLength = buffer.Length;
            response.ContentLength64 = contentLength;

            using (var output = response.OutputStream)
            {
                using (var writer = new BinaryWriter(output))
                {
                    writer.Write(buffer);
                    writer.Flush();
                }
            }
        }
```
