### ISSUE TITLE
api serving throws an error in some cases

### ISSUE THREAD

**Issue by da3dsoul** [japanesemediamanager/ShokoServer#627]
I'm getting these in debugging (suppressed in release)
```
System.Net.HttpListenerException (0x80004005): The I/O operation has been aborted because of either a thread exit or an application request
at System.Net.HttpResponseStream.Write(Byte[] buffer, Int32 offset, Int32 size)
at System.IO.BinaryWriter.Write(Byte[] buffer)
at Nancy.Hosting.Self.NancyHost.OutputWithContentLength(Response nancyResponse, HttpListenerResponse response)
at Nancy.Hosting.Self.NancyHost.ConvertNancyResponseToResponse(Response nancyResponse, HttpListenerResponse response)
at Nancy.Hosting.Self.NancyHost.Process(HttpListenerContext ctx)
```
The response is returned as expected, but it gives this.
@hidden4003 @Cazzar any idea what it means or how to fix it?
I reproduce this with api/file/unsort

**Comment by da3dsoul** [comment]
Put a breakpoint at Line 1568 in ShokoServer.cs to catch it

**Comment by bigretromike** [comment]
I tested this with clean db and latest server and few series and few unknown series, and I'm unable to reproduce this.
nor exception is trigger nor the log show any error
I'm using fiddler with proper `apikey` and `/api/file/unsort` even when spaming I don't see error. 

Is this a still a thing (with maybe bigger db) or this got fixed ?

**Comment by Cazzar** [comment]
With my main db I've not had any time-outs on this and I had a monitor happening off of that API call

**Comment by da3dsoul** [comment]
Huh. Okay, well I'll reopen if I care enough
